config/routes.rb
Rails.application.routes.draw do
	resources :bills

	root 'bills#home'		
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
	validates :name, presence: true
	validates :price, presence: true
	
	has_many :recipients, inverse_of: :bill
	accepts_nested_attributes_for :recipients, reject_if: :all_blank

end

app/models/recipient.rb
class Recipient < ApplicationRecord
  belongs_to :bill
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
	def index
		@bills = Bill.all
	end

	def new
		@bill = Bill.new
		@bill.recipients.build
		@bill.recipients.build
	end

	def create
		
		if Bill.create(bill_params)
			redirect_to action: :index

		else 
			render :new
		end
	end

	def show
		@bill = Bill.find(params[:id])
	end

	def home
		@bill = Bill.last
		
	end

	def bill_params
		params.require(:bill).permit(:name, :price, :description, :bank_account, recipients_attributes: [:name, :email])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def split_bill(price, person_count)
		array = []
		person_count.times { array << price/person_count }
		(price%person_count).times { |i| array[i] += 1 }
 		array
 	end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_panel.html.erb
<article class="panel <%= local_assigns[:classes].present? ? classes : '' %>">
  <header class="panel__header">
    <%= image_tag 'icon-coin.svg', class: "panel__image" %>

    <div class="panel__heading">
      <h3 class="panel__title"><%= link_to bill.name, bill_path(bill.id) %></h3>

      <p class="panel__text">
        <%= bill.created_at.strftime('%d') %>

        <%= bill.created_at.strftime('%b') %>
      </p>
    </div>

    <p class="panel__price"><%= bill.price %> PLN</p>
  </header>

  <section class="panel__details">
    <ul class="panel__icons">
      <% bill.recipients.take(3).each do %>
        <li class="panel__icon"></li>
      <% end %>

    <% if bill.recipients.count > 3 %>
      <li class="panel__counter">+<%= bill.recipients.count - 3%></li>
    <% end %>

  </section>
</article>

app/views/bills/_recipient.html.erb
<article class="recipient js_recipient" id="<%= recipient.id %>">
  <input type="checkbox" id="<%= recipient.id %>" class="recipient__input js_recipient-input">

  <span class="recipient__input-placeholder" role="placeholder"></span>

  <%= image_tag 'image-placeholder-small-green.svg', class: "recipient__image" %>

  <section class="recipient__details">
    <p class="recipient__title"><%= recipient.name %></p>

    <p class="recipient__text"><%= recipient.email %></p>
  </section>

  <label for="<%= recipient.id %>" class="recipient__label"><%= prices[index] %></label>
</article>

app/views/bills/_recipient_fields.html.erb
<div class="form__part form__part--flex nested-fields">
  <%= image_tag "image-placeholder-small-green", class: 'form__image' %>

  <%= f.input :name, wrapper_html: { class: 'form__field form__field--spaced' }, placeholder: 'Name*' %>

  <%= f.input :email, wrapper_html: { class: 'form__field form__field--spaced' }, placeholder: 'E-mail address*' %>

  <%= link_to_remove_association 'remove', f, class: 'button button--cancel' %>
</div>

app/views/bills/home.html.erb
<section class="home">
  <figure class="home__depiction">
    <%= image_tag "icon-welcome", class:"depiction__image" %>

    <div class="home__description">
      <p class="home__text">
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
      </p>

      <%= link_to 'Create new bill', new_bill_path, class: "home__action button" %>
    </div>
  </figure>

  <h4 class="home__heading">Recent bills:</h4>

  <% if @bill.present? %>
  <%= render 'panel', bill: @bill %>

  <%= link_to 'Full bill history', '/bills', class: "button home__action" %>
  <% else %>
  <figure class="home__status">
    <%= image_tag "icon-welcome", class:"depiction__image" %>
  </figure>
  <% end %>
</section>

app/views/bills/index.html.erb
<section class="summary">
  <div class="summary__heading">
    <h1 class="summary__title">Bill list</h1>
  </div>

  <ul class="summary__list">
    <% @bills.each do |bill| %>
    <li class="summary__item">
      <%= render 'panel', bill: bill %>
    </li>
    <% end %>
  </ul>
</section>

app/views/bills/new.html.erb
<section class="create">
  <%= simple_form_for @bill, defaults: { input_html: { class: 'form__input' }, label_html: { class: 'form__label' }, wrapper_html: { class: 'form__field'} } do |f|%>
    <div class="form">
      <div class="form__part">
        <h4 class="form__heading">Bill description</h4>

        <div class="form__part form__part--flex">
          <div class="form__field-wrapper form__field-wrapper--spaced">
            <%= image_tag "icon-invoice.svg", class: "form__icon" %>

            <%= f.input :name, placeholder: "eg. Cinema Tickets" %>
          </div>

          <div class="form__field-wrapper form__field-wrapper--spaced">
            <%= f.input :price, placeholder: 'eg. 23.45' %>
          </div>
        </div>

        <div class="form__field-wrapper">
          <%= image_tag "icon-piggy-bank.svg", class: "form__icon" %>

          <%= f.input :bank_account, placeholder: '48 1234 5678 980' %>
        </div>
      </div>

      <div class="form__part">
        <h4 class="form__heading">Recipients</h4>

        <%= f.simple_fields_for :recipients do |recipient| %>
        <%= render 'recipient_fields', f: recipient %>
        <% end %>

        <div class="form__action">
          <%= link_to_add_association 'Add new person', f, :recipients, class: 'button' %>
        </div>
      </div>

      <div class="form__part">
        <h4 class="form__heading">Additional Info</h4>

        <div class="form__field-wrapper">
          <%= image_tag "icon-notes.svg", class: "form__icon" %>

          <%= f.input :description, placeholder: 'Notes' %>
        </div>
      </div>

      <div class="form__actions">
        <%= link_to 'cancel', bills_path, class: 'button button--flat'%>

        <%= f.button :submit, class: 'button' %>
      </div>
    </div>
  <% end %>
</section>

app/views/bills/show.html.erb
<article class="bill" id='<%= @bill.id %>'>
  <header class="bill__header">
    <%= link_to '', bills_path, class: 'button button--cancel bill__close' %>

    <h1 class="bill__title"><%= @bill.name %></h1>

    <h2 class="bill__subtitle"><%= @bill.price %></h2>

    <div class="bill__flex-list">
      <%= image_tag "icon-invoice.svg", class: "bill__icon"%>

      <div>
        <h2 class="bill__heading-small">Bill’s URL</h2>
        <h3 class="bill__text"><%= bill_url(@bill.id) %>  </h3>
      </div>
    </div>
  </header>

  <% if @bill.bank_account.present? %>
  <section class="bill__segment">
    <h3 class="bill__heading-medium">Settle up</h3>

    <div class="bill__flex-list">
      <%= image_tag "icon-piggy-bank.svg", class: "bill__icon"%>

      <div>
        <h2 class="bill__heading-small">Backer’s account number</h2>
        <h3 class="bill__text"><%= @bill.bank_account %></h3>
      </div>
    </div>
  </section>
  <% end %>

  <section class="bill__segment">
    <h4 class="bill__heading-medium">Recipients</h4>

    <% if @bill.recipients.present? %>
      <% prices = split_bill(@bill.price, @bill.recipients.count) %>
      <ul>
        <% @bill.recipients.each_with_index do |recipient, index| %>
        <li class="bill__item">
           <%= render 'recipient', recipient: recipient, index: index, prices: prices %>
        </li>
        <% end %>
      </ul>
    <% else %>
    <p class="bill__text">No recipients added</p>
    <% end %>
  </section>

  <section class="bill__segment">
    <h4 class="bill__heading-medium">Additional information</h4>

    <% if @bill.description %>
      <p>
        <%= @bill.description %>
      </p>
    <% else %>
      <p class="bill__text">No description added</p>
    <% end %>
  </section>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Splitt App</title>

    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="app">
      <%= image_tag ("background-shape.png"), class: "background background--top", alt: "background image" %>

      <%= image_tag ("background-shape.png"), class: "background background--bottom", alt: "background image" %>

      <header class="header">
        <%= link_to "/", class:" header__logo" do %>
          <%= image_tag "logo.svg", class:"header__logo" %>
        <% end %>
      </header>

      <main>
        <%= yield %>
      </main>
    </div>
  </body>
</html>